language: c
compiler: gcc
sudo: false
addons:
  apt:
    packages:
    - libfftw3-dev
    - check

branches:
  only:
    - master

before_script:
  - autoreconf --install

script:
  - ./configure && make && make check

after-failure:
  - cat tests/test-suite.log
