language: c
compiler: gcc
sudo: false
addons:
  apt:
    packages:
    - libfftw3-dev
    - check

branches:
  only:
    - master

before_script:
  - autoreconf --install
  - ./configure

script:
  - make && make check

after_success:
  - skip_cleanup: true
  - echo -e "\e[32m( \u00b4 \u25bd \` )b\e[0m"
  - ls -AR .
#
#after_failure:
#  - echo -e "\e[31m(╯°□°)╯︵ ┻━┻\e[0m"
